### ISSUE TITLE
Rank Badges vs Speed Modifiers

### ISSUE THREAD

**Issue by HyperBeast43** [semicola/Rap-Ability-Test#1] opened 2024-06-05 00:59 UTC
Currently, all speeds give the same rank badge, even though beating a song at 3x speed is much more of a feat than 0.5x.

**Comment by skedgyedgy** [comment] 2024-06-09 01:18
-- This is not a bug, and rank badges are purely local. Closing.

**Closed as not planned** 2024-06-09 01:18 UTC
Labels: invalid, wontfix
